### ISSUE TITLE
Errors when deploying since today

### ISSUE THREAD

**Issue by nikgraf** [alex-murashkin/serverless-plugin-tracing#10]
Since today I'm receiving these errors when deploying an application with the tracing plugin enabled:

```
Serverless: Tracing ENABLED for function "func1"
Serverless: Tracing ENABLED for function "func2"
Serverless: Tracing ENABLED for function "func3"
Serverless: Tracing ENABLED for function "func4"
Serverless: Tracing ENABLED for function "func5"
 
  Serverless Error ---------------------------------------
 
  The function could not be updated due to a concurrent update operation.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           8.7.0
     Serverless Version:     1.23.0
```

Any ideas why this is happening? Maybe throttling would help?

P.S: I replaced the func names  ;)

**Comment by alex-murashkin** [comment]
Hi @nikgraf, I'll try to reproduce it this weekend and see if I can fix it.
Just to confirm: 
1. you have 5 functions in total, correct?
2. is it intermittent?
Thanks!

**Comment by nikgraf** [comment]
Today it started to happen for two services. One with 12, the other with 5 functions. I upgraded to the latest version of your plugin, but the problem still persisted. Right now I'm disabling it until it is fixed. 

Thanks for getting back so quickly.

**Comment by alex-murashkin** [comment]
Thanks for the info, just another question: did you happen to bump the version of `serverless` framework or node.js version at some point? How long have you been using serverless `1.23.0` and `node 8.7` for?

**Comment by nikgraf** [comment]
Yes, indeed. I bumped the version of the framework. What's interesting though is that we have one service with 8 functions with the plugin enabled and it works fine.

**Comment by alex-murashkin** [comment]
Interesting! OK, I think I have enough info to proceed, I'll keep you posted. Thanks!

**Comment by alex-murashkin** [comment]
FYI: my co-worker has just reported the exact same issue, and also since today. And he didn't seem to do any version bumps or anything. Feels like something has changed on AWS today.

**Comment by alex-murashkin** [comment]
@nikgraf 
Just published `serverless-plugin-tracing@2.0.0` that uses Cloud Formation for setting tracing value.
We tested it with serverless `1.22.0`, but should work in later version as well. Could you please check? No change on your part (other than version bump) should be required.

**Comment by nikgraf** [comment]
Works like a charm! Thanks @alex-murashkin 👏

**Comment by andrhamm** [comment]
I'm having the same issue on serverless 1.27.2. Any ideas?
