### ISSUE TITLE
Setting tracing via CloudFormation

### ISSUE THREAD

**Issue by sime** [alex-murashkin/serverless-plugin-tracing#9]
Just a comment, this plugin could be simplified by setting tracing via CloudFormation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-function-tracingconfig.html

If I find the will, I might put together a PR. But no promises.

Otherwise, thanks, plugin worked first time.

**Comment by alex-murashkin** [comment]
`+ serverless-plugin-tracing@2.0.0`
